name: zhebsa_assistant
description: Dzongkha to Zhebsa Translation app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2
  path_provider: ^2.0.8
  flutter_switch: ^0.3.2
  get: ^4.6.1  
  flutter_share: ^2.0.0
  audioplayers: ^0.20.1  
  responsive_framework: ^0.1.7  
  dio: ^4.0.6
  permission_handler: ^9.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audio/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Joyig
      fonts:
        - asset: assets/fonts/Joyig-Regular.ttf
    - family: Uchen
      fonts:
        - asset: assets/fonts/DDC-Uchen.ttf
    - family: Wangdi
      fonts:
        - asset: assets/fonts/Wangdi_29.ttf
    - family: Jomolhari
      fonts:
        - asset: assets/fonts/Jomolhari.ttf
    - family: Rinzin
      fonts:
        - asset: assets/fonts/DDC-Rinzin.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
          # weight: 700
          # style: italic

flutter_native_splash:
  # color: "#42a5f5"
  background_image: "assets/images/background.png"
  image: "assets/images/rgob_logo.png"
